[build]
  functions = "netlify/functions"
  command = "cd netlify/functions && npm install"

[dev]
  functions = "netlify/functions"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core" 